sonar.projectKey=pedroigor-dev_projeto-lastro
sonar.projectName=Projeto Lastro
sonar.sources=backend/src/main,frontend/src/app
sonar.tests=backend/src/test,frontend/src/app
sonar.test.inclusions=**/*Test.java,**/*.spec.ts
sonar.java.binaries=backend/target/classes
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**
